sudo: true
language: cpp
branches:
  only:
  - master
os:
  - linux
  - osx
compiler:
  - gcc
before_install:
  - sudo apt-get update -qq
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update          ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install graphviz; fi


script:
  - make all
  - ./tatakai.x86_64
