sudo: false
language: cpp
branches:
  only:
  - master
os:
  - linux
before_install:
- sudo apt-get update -qq
- sudo apt-get install -qq wine xorg
script:
  - sudo touch ~/.Xauthority && xauth generate :0 . trusted && xauth add ${HOST}:0 . $(xxd -l 16 -p /dev/urandom) && startx
  - wine tatakai.exe
  - ./tatakai.x86_64
