sudo: true
language: cpp
branches:
  only:
  - master
os:
  - linux
  - osx
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq wine xorg
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update          ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install graphviz; fi
  - sudo touch ~/.Xauthority && sudo xauth generate :0 . trusted && xauth add ${HOST}:0 . $(xxd -l 16 -p /dev/urandom) && startx

script:
  - make all
  - wine tatakai.exe
  - ./tatakai.x86_64
